```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
```
```{r}
df <- read_csv("data/data_5000.csv")
df
```

```{r}
df_year <- df |>
  group_by(year, casing) |> summarize(count = n()) |>
  group_by(year) |>
  mutate(total_count = sum(count)) |>
  mutate(proportion = count / total_count)

  
df_year |>
  filter(casing == "upper") |>
  ggplot(aes(x = year, y = proportion, fill)) +
  geom_bar(stat = "identity", fill = "#e77d72") +
  labs(title = "Proportion of Songs with Uppercase Titles by Year",
       x = "Year",
       y = "Proportion") +
  scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 1)) +
  scale_y_continuous(limits = c(0, 0.35)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

df_year |>
  filter(casing == "lower") |>
  ggplot(aes(x = year, y = proportion, fill)) +
  geom_bar(stat = "identity", fill = "#61bfbc") +
  labs(title = "Proportion of Songs with Lowercase Titles by Year",
       x = "Year",
       y = "Proportion") +
  scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 1)) +
  scale_y_continuous(limits = c(0, 0.35)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}
df |>
  ggplot(aes(x = is_uniform, y = birth_year)) +
  geom_boxplot() +
  scale_y_reverse() + 
  labs(title = "Age Distribution of Artists by Song Title Capitalization",
       x = "Title Capitalization",
       y = "Artist Birth Year")
```
```{r}
t_test_result <- t.test(birth_year ~ is_uniform, data = df)
print(t_test_result)
```

```{r}
df_gender <- df |> group_by(casing, gender) |> summarize(count = n()) |>
  mutate(total_count = sum(count)) |>
  mutate(proportion = count / total_count) |>
  filter(casing != "mixed")

df_gender |>
  ggplot(aes(x = casing, y = proportion, fill = gender)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0.65, linetype = "dashed", color = "black") +
  scale_fill_manual(values = c("male" = "#1F77B4", "female" = "#FF77B4")) +
  labs(title = "Gender Ratio of Artists by Song Title Capitalization",
       x = "Title Capitalization",
       y = "Proportion")
```
```{r}
table <- table(df$gender, df$casing)
chi2_test_result <- chisq.test(table)
print(chi2_test_result)
```

```{r}
df_bb <- read_csv("data/data_billboard.csv")
df_bb
```

```{r}
df_long <- df_bb |>
  pivot_longer(cols = c(energy, valence), names_to = "metric", values_to = "value")

df_long |>
  ggplot(aes(x = casing, y = value)) +
  geom_boxplot() +
  facet_wrap(~ metric) +
  labs(title = "Distribution of Energy and Valence Ratings by Song Title Capitalization",
       x = "Title Capitalization",
       y = "Rating")
```
```{r}
lowercase_songs <- df_bb %>% filter(casing == "lower")
non_lowercase_songs <- df_bb %>% filter(casing != "lower")

t_test_energy_lower <- t.test(lowercase_songs$energy, non_lowercase_songs$energy)
t_test_valence_lower <- t.test(lowercase_songs$valence, non_lowercase_songs$valence)

uppercase_songs <- df_bb %>% filter(casing == "upper")
non_uppercase_songs <- df_bb %>% filter(casing != "upper")

t_test_energy_upper <- t.test(uppercase_songs$energy, non_uppercase_songs$energy)
t_test_valence_upper <- t.test(uppercase_songs$valence, non_uppercase_songs$valence)

print(t_test_energy_lower)
print(t_test_valence_lower)
print(t_test_energy_upper)
print(t_test_valence_upper)

```
